I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Course_Select.rpy", line 21, in script call
    $renpy.call(extras[choice][0])
  File "game/Course_Select.rpy", line 23, in script
    $course.progressClass()
  File "game/Course_Select.rpy", line 23, in <module>
    $course.progressClass()
  File "game/Course.rpy", line 22, in progressClass
    if (unlocked):
NameError: global name 'unlocked' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/Course_Select.rpy", line 21, in script call
    $renpy.call(extras[choice][0])
  File "game/Course_Select.rpy", line 23, in script
    $course.progressClass()
  File "C:\Users\k1029\Desktop\Coding\renpy-7.4.11-sdk/renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\k1029\Desktop\Coding\renpy-7.4.11-sdk/renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/Course_Select.rpy", line 23, in <module>
    $course.progressClass()
  File "game/Course.rpy", line 22, in progressClass
    if (unlocked):
NameError: global name 'unlocked' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
RenPy22 1.0
Mon Mar 14 22:00:19 2022
